-- =============================================================================
-- Experience Rate Analysis System - Schema (SQLite)
-- =============================================================================
-- Normalized SQLite schema for individual medical insurance experience-rate
-- analysis and population-based disease incidence-rate benchmarks.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- parameters: global settings (single row)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parameters (
    id                           INTEGER PRIMARY KEY CHECK (id = 1),
    observation_year_end_month   INTEGER NOT NULL
                                 CHECK (observation_year_end_month BETWEEN 1 AND 12),
    fiscal_year_end_month        INTEGER NOT NULL DEFAULT 9
                                 CHECK (fiscal_year_end_month BETWEEN 1 AND 12)
);

-- -----------------------------------------------------------------------------
-- rider_def: rider definitions (rider master serving as the aggregation axis for experience-rate analysis)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rider_def (
    rider_code           TEXT PRIMARY KEY,
    rider_name           TEXT NOT NULL,
    rider_category       TEXT,                    -- e.g. 'medical' / 'cancer' / 'dread_disease'
    display_order        INTEGER NOT NULL DEFAULT 0,
    description          TEXT
);

-- -----------------------------------------------------------------------------
-- population_incidence: population-based disease incidence-rate table
-- -----------------------------------------------------------------------------
-- Loads data/processed/incidence_panel.csv generated by
-- scripts/build_incidence_panel.py.
--
-- rate_type:
--   'registry'       : incidence rate from the National Cancer Registry (true incidence, highest quality)
--   'initial_visit'  : approximation based on outpatient initial-visit utilization rate from Patient Survey Z70/Z13
--   'discharge'      : new hospitalization rate computed from Patient Survey Z10 / average length of stay
--   'mortality'      : mortality rate from Vital Statistics (approximation capped by case fatality)
--   'prevalence_adj' : incidence back-calculated as utilization rate / average disease duration
--
-- quality_flag: A(true incidence) / B(initial-visit approx.) / C(discharge approx.) / D(mortality approx.)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS population_incidence (
    disease_id              TEXT,              -- e.g. 'cancer', 'heart_disease' (NULL allowed if unclassified)
    disease_norm            TEXT NOT NULL,     -- Japanese disease name (part of PK)
    icd10                   TEXT,              -- ICD-10 code (mainly from the cancer registry)
    sex                     INTEGER NOT NULL CHECK (sex IN (0, 1, 2)),
                            -- 0=total, 1=male, 2=female
    age_code                TEXT NOT NULL,     -- e.g. 'a05_09', 'a60_64', 'a90p'
    age_low                 INTEGER,           -- lower bound of age interval (inclusive)
    age_high                INTEGER,           -- upper bound of age interval (inclusive, NULL for open interval)
    year                    INTEGER NOT NULL,  -- calendar year (CE)
    section                 TEXT NOT NULL DEFAULT 'total',
                            -- 'total' / 'inpatient' / 'outpatient' / 'onset'
    rate_type               TEXT NOT NULL CHECK (rate_type IN
                            ('registry', 'initial_visit', 'discharge',
                             'mortality', 'prevalence_adj')),
    incidence_rate_annual   REAL,              -- annual rate (dimensionless 0-1)
    incidence_rate_per_100k REAL,              -- per 100,000 population
    numerator_count         REAL,              -- numerator (actual/estimated count)
    population_thousand     REAL,              -- denominator (thousands of people)
    source_table            TEXT,              -- source file / statsDataId
    quality_flag            TEXT,              -- 'A' / 'B' / 'C' / 'D'
    method_note             TEXT,              -- notes on the estimation method
    PRIMARY KEY (disease_norm, sex, age_code, year, section, rate_type)
);

CREATE INDEX IF NOT EXISTS idx_population_incidence_disease_year
    ON population_incidence(disease_id, year);

CREATE INDEX IF NOT EXISTS idx_population_incidence_age
    ON population_incidence(age_low, age_high);

-- -----------------------------------------------------------------------------
-- rider_disease_map: mapping between riders (rider_code) and diseases (disease_id)
-- -----------------------------------------------------------------------------
-- When one rider spans multiple diseases, weight is used for apportionment.
-- preferred_rate_type is "which rate_type is the first choice as this rider's incidence rate".
-- -----------------------------------------------------------------------------
-- rider_def is treated as a loosely coupled display lookup; no FK is set.
-- (rider_def is auto-populated at load-incidence time with rider_code values
--  derived from rider_disease_map.csv)
CREATE TABLE IF NOT EXISTS rider_disease_map (
    rider_code            TEXT NOT NULL,
    disease_id            TEXT NOT NULL,
    weight                REAL NOT NULL DEFAULT 1.0,  -- apportionment factor at disease granularity
    preferred_rate_type   TEXT,                        -- first-choice rate_type
    note                  TEXT,
    PRIMARY KEY (rider_code, disease_id)
);

-- -----------------------------------------------------------------------------
-- scalebb_run: run history of the Scale BB extension model (fit / project metadata)
-- -----------------------------------------------------------------------------
-- One row is added per scripts/scale_bb_disease.py fit / project run.
-- config_json stores the ScaleBBConfig (lam_row, lam_col, long_term_rate,
-- convergence_year, horizon, age_taper_start/end, etc.) as-is in JSON.
--
-- kind:
--   'fit'          : Phase 1 smoothing only (rate_observed + rate_smoothed + improvement_*)
--   'projection'   : Phase 2 projection (long-term-rate blending + rate_projected)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scalebb_run (
    run_id              TEXT PRIMARY KEY,
    kind                TEXT NOT NULL CHECK (kind IN ('fit', 'projection')),
    source_panel        TEXT,              -- e.g. 'mortality_apc' / 'age_period'
    diseases            TEXT,              -- comma-separated target disease_id values
    sex                 TEXT,              -- 'total' / 'male' / 'female'
    section             TEXT,              -- 'total' / 'inpatient' / 'outpatient'
    age_min             INTEGER,
    age_max             INTEGER,
    year_min            INTEGER,
    year_max            INTEGER,
    long_term_rate      REAL,
    convergence_year    INTEGER,
    horizon_year        INTEGER,
    lam_row             REAL,
    lam_col             REAL,
    config_json         TEXT,              -- full serialization of ScaleBBConfig
    source_file         TEXT,              -- source CSV/parquet file
    note                TEXT,
    created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- -----------------------------------------------------------------------------
-- scalebb_improvement: Phase 1 fit results (smoothed improvement rates over the observation period)
-- -----------------------------------------------------------------------------
-- 1 row = one (run_id, disease_id, sex, section, age, year) combination.
-- rate_observed        : input observed rate (per 100,000)
-- rate_smoothed        : rate after Whittaker-Henderson 2D smoothing
-- improvement_observed : annualized improvement rate computed from observed rates (t-1 -> t geometric mean)
-- improvement_smoothed : annualized improvement rate computed from smoothed rates
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scalebb_improvement (
    run_id               TEXT NOT NULL,
    source_stream        TEXT,              -- e.g. 'mortality_apc/cancer'
    disease_id           TEXT NOT NULL,
    sex                  TEXT NOT NULL,
    section              TEXT NOT NULL DEFAULT 'total',
    age                  INTEGER NOT NULL,
    year                 INTEGER NOT NULL,
    rate_observed        REAL,
    rate_smoothed        REAL,
    improvement_observed REAL,
    improvement_smoothed REAL,
    PRIMARY KEY (run_id, disease_id, sex, section, age, year),
    FOREIGN KEY (run_id) REFERENCES scalebb_run(run_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_scalebb_improvement_disease_year
    ON scalebb_improvement(disease_id, year);

-- -----------------------------------------------------------------------------
-- scalebb_projection: Phase 2 projection results (composite series of observed + future)
-- -----------------------------------------------------------------------------
-- 1 row = one (run_id, disease_id, sex, section, age, year) combination (year up to horizon)
-- is_observed          : 1=observed year, 0=future projection year
-- improvement_final    : improvement rate linearly converged to the long-term rate L via the original paper's h(y) formula
-- rate_projected       : projected rate cumulatively generated from base_year using improvement_final
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scalebb_projection (
    run_id               TEXT NOT NULL,
    source_stream        TEXT,
    disease_id           TEXT NOT NULL,
    sex                  TEXT NOT NULL,
    section              TEXT NOT NULL DEFAULT 'total',
    age                  INTEGER NOT NULL,
    year                 INTEGER NOT NULL,
    is_observed          INTEGER NOT NULL DEFAULT 0,
    improvement_final    REAL,
    rate_projected       REAL,
    PRIMARY KEY (run_id, disease_id, sex, section, age, year),
    FOREIGN KEY (run_id) REFERENCES scalebb_run(run_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_scalebb_projection_disease_year
    ON scalebb_projection(disease_id, year);

CREATE INDEX IF NOT EXISTS idx_scalebb_projection_observed
    ON scalebb_projection(is_observed, disease_id);

-- -----------------------------------------------------------------------------
-- scalebb_cohort_effect: side table for the APC extension's cohort effect γ(c)
-- -----------------------------------------------------------------------------
-- Stores γ(cohort) computed by fit_scale_bb_apc in
-- scripts/scale_bb_apc_model.py. cohort = year - age (birth year equivalent).
-- 1 row = one (run_id, disease_id, sex, section, cohort) combination.
--
-- Due to the second-difference penalty, the absolute level of γ(c) is
-- unidentified (constant + linear indeterminacy), but relative differences
-- between cohorts (e.g. the 1950 generation vs the 1970 generation) are interpretable.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scalebb_cohort_effect (
    run_id               TEXT NOT NULL,
    disease_id           TEXT NOT NULL,
    sex                  TEXT NOT NULL,
    section              TEXT NOT NULL DEFAULT 'total',
    cohort               INTEGER NOT NULL,   -- birth year (year - age)
    gamma                REAL,               -- γ(cohort) log-scale effect
    is_observed          INTEGER NOT NULL DEFAULT 1,  -- 1=observed within fit, 0=extrapolated
    PRIMARY KEY (run_id, disease_id, sex, section, cohort),
    FOREIGN KEY (run_id) REFERENCES scalebb_run(run_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_scalebb_cohort_disease
    ON scalebb_cohort_effect (disease_id, sex, cohort);

-- -----------------------------------------------------------------------------
-- predicted_rate_generational: per-issue-year 1D assumed incidence-rate table (for downstream distribution)
-- -----------------------------------------------------------------------------
-- scalebb_projection (3D: sex x age x year) sliced by Generational Projection
-- into a downstream-system-compatible [sex, age] lookup format.
--
-- Formula: rate_per_100k[issue_year, sex, age]
--       = scalebb_projection.rate_projected[sex, age, year = issue_year + (age - issue_age)]
--
-- This lets downstream systems (policy administration / reserve calculation)
-- benefit from this research model while keeping their existing [sex, age]
-- lookup API (issue_year is selected from policy attributes).
--
-- Reference example (downstream SQL):
--   SELECT rate_per_100k FROM predicted_rate_generational
--   WHERE disease_id = :disease AND sex = :policy_sex
--     AND issue_year = :policy_issue_year AND age = :policy_current_age;
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS predicted_rate_generational (
    run_id               TEXT NOT NULL,
    disease_id           TEXT NOT NULL,
    sex                  TEXT NOT NULL,      -- 'total' / 'male' / 'female'
    section              TEXT NOT NULL DEFAULT 'total',
    issue_year           INTEGER NOT NULL,   -- policy issue year (table-version axis)
    issue_age            INTEGER NOT NULL,   -- issue age (usually 0 or product-specific)
    age                  INTEGER NOT NULL,   -- lookup age (>= issue_age)
    rate_per_100k        REAL,
    year_lookup          INTEGER,             -- corresponding calendar year = issue_year + (age - issue_age)
    PRIMARY KEY (run_id, disease_id, sex, section, issue_year, issue_age, age),
    FOREIGN KEY (run_id) REFERENCES scalebb_run(run_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pred_rate_gen_lookup
    ON predicted_rate_generational (disease_id, sex, issue_year, age);

CREATE INDEX IF NOT EXISTS idx_pred_rate_gen_run
    ON predicted_rate_generational (run_id);
